### ISSUE TITLE
[REQUEST] Remember and restore position after selecting a process

### ISSUE THREAD

**Issue by avently** [aristocratos/bpytop#14]
**Is your feature request related to a problem? Please describe.**
After pressing on `Enter` I see a mini window at the top with additional information about process. Then I'm clicking `arrow down`, or `arrow up`, or `enter` and expect that cursor will be moved to a process that was selected before pressing enter but the cursor (i.e. selected item in the list of processes) moves to the start of the list in window which is not super useful.  

**Describe the solution you'd like**
Instead I propose to remember the position of process that was selected and then to restore that position and highlight it in the list.

**Comment by aristocratos** [comment]
This is intentional to give the details box focus since the "terminate", "kill", "interrupt" commands isn't active for the detailed process if selection is greater than 0. For quick change between which process to show details for you can double click any process in the list.

But I would like to hear some peoples opinion if this is a wanted change.

**Comment by aristocratos** [comment]
Oh wait, I just realized what you meant. Save the and restore the position is quite doable :)

**Comment by drazil100** [comment]
I might argue to restore the selection of the process that you exited the info view of rather than the position of the cursor was on the list since the process can move around on the list and it would make sense to exit highlighting what you were just inspecting. 

That said restoring the exact position of the list would be about just as fine.

**Comment by avently** [comment]
@aristocratos after updating to the latest version from github (via Aur) I'm unable to run the app. So it's crashes when I try to launch it:
```
06/08/20 (14:22:35) | ERROR: Data collection thread failed with exception: list index out of range
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2338, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 2530, in _draw
    CpuBox._draw_fg()
  File "/usr/bin/bpytop", line 1548, in _draw_fg
    out += f'{THEME.inactive_fg}  ⡀⡀⡀⡀⡀{Mv.l(5)}{THEME.gradient["temp"][cpu.cpu_temp[n][-1]]}{Graphs.temps[n](None if cls.resized else cpu.cpu_temp[n][-1])}'
IndexError: list index out of range
06/08/20 (14:22:35) | WARNING: Exiting with errorcode (1). Runtime 0:00:00 
```

**Comment by aristocratos** [comment]
@avently 

Fixed in v1.0.6

**Comment by avently** [comment]
Crash fixed too, thanks. Did you decide to not restore last selected position in a list after pressing enter to close info panel?
I mean, now you can press enter and focus will be moved to info panel, then you can press enter again and focus will be on the first position in the list. Is it expected?

**Comment by aristocratos** [comment]
Forgot to add restore to "enter" also. Will do in next update.

**Comment by avently** [comment]
@aristocratos position restore works perfectly, thank you for your time!

**Comment by mci07** [comment]
Can we talk ?

Dikirim dari iPhone saya

**Comment by aristocratos** [comment]
@mci07 

Is that rhetorical?
