### ISSUE TITLE
[BUG] Battery stats symbol is wrong in bpytop>=1.0.39

### ISSUE THREAD

**Issue by remisalmon** [aristocratos/bpytop#140]
**Describe the bug**

Battery stats shows the battery discharging when plugged in on bpytop>=1.0.39.

**To Reproduce**

Run bpytop>=1.0.39 when the battery is charging or fully charged with Show battery = True: the battery stats shows the discharging icon (▼).

**Expected behavior**

The correct icon should be displayed. The correct icon is displayed with bpytop==1.0.38.

The bug was most probably introduced in commit 77f9db0edf5d4aab941fa697d8a12b2748c454d3.

**Screenshots**

![image](https://user-images.githubusercontent.com/26257211/95368876-ee876f00-0893-11eb-901f-1cdb82abe390.png)

**Info (please complete the following information):**
 - bpytop version: 1.0.40
 - psutil version: 5.7.2
 - (Linux) Linux distribution and version: Fedora 32
 - Terminal used: GNOME Terminal
 - Font used:
 - Python version: 3.8.5

**Additional context**

No errors in the log.

**Comment by aristocratos** [comment]
@remisalmon 
This is most likely caused by psutil and the status check in bpytop reading from different battery sensors.

You can test this by looking at how many folders you've got in `/sys/class/power_supply/`, I would guess that you've got more than one. Should be able to fix it by using the same sorting as psutil for the battery detection.

Will be fixed in next update.

**Comment by aristocratos** [comment]
Fixed in v1.0.42

**Comment by remisalmon** [comment]
1.0.42 works for me, thanks.
