### ISSUE TITLE
[Q] How much performance gain will there be if this was ported to golang or rust?

### ISSUE THREAD

**Issue by NightMachinary** [aristocratos/bpytop#177]
Currently,`bpytop` uses around 4-6% CPU constantly, which disallows leaving it running in the background.

**Comment by aristocratos** [comment]
@NightMachinary 
Cpu usage is dependant on your specific cpu, frequency, os and python version.
For reference, bpytop uses less cpu than glances, gtop and about as much as gotop.

Looking at ytop written in rust, it uses about half as much cpu, but it also has a more minimalist UI.

There will likely be a rust version some time in the future, but not so much for performance reasons, but more as a project for me to learn rust.

If you need a lightweight proc monitor, htop is probably still the best alternative with about 1/4 - 1/5 of the usage bpytop has.

**Comment by alerque** [comment]
I might be interested in contributing if work on a Rust port ever gets moving. The [ytop](https://github.com/cjbassi/ytop) project has been shelved, although [bottom](https://github.com/ClementTsang/bottom) looks like a pretty equivalent system. I really like the lighter footprints of that and `htop`, but the eye candy in this project is staggering. I'd love to play around with making Rust TUIs this beautiful. Not so much because I need the system monitoring as that I'd like some of my other Rust projects to benefit. Please anybody that wants to start this effort drop a ping to me.

**Comment by GTANAdam** [comment]
I might start porting this to golang soon

**Comment by aristocratos** [comment]
@GTANAdam 

Well I just released the C++ version https://github.com/aristocratos/btop

That might be a better base to use for a port to Go

Good luck regardless of what you decide, and I wouldn't mind if you keep me updated how it goes :)

**Comment by GTANAdam** [comment]
> @GTANAdam
> 
> Well I just released the C++ version https://github.com/aristocratos/btop
> 
> That might be a better base to use for a port to Go
> 
> Good luck regardless of what you decide, and I wouldn't mind if you keep me updated how it goes :)

I've just noticed it, thank you for this piece of software, there's basically no reason to port to Golang if there's a C++ version
