### ISSUE TITLE
[REQUEST] Add support for non-truecolor terminals

### ISSUE THREAD

**Issue by mspielberg** [aristocratos/bpytop#189]
**Is your feature request related to a problem? Please describe.**
bpytop requires a truecolor-capable terminal, without any capability to gracefully degrade.

**Describe the solution you'd like**
A configuration option to use other escape codes to specify color, at least the common xterm 256-color mode, and if possible for the legacy ANSI 16 color mode.

**Describe alternatives you've considered**
Autodetecting terminal support for truecolor seems infeasible at this time, particularly since so many terminals self-report as `xterm` or similarly generic terminals.

**Additional context**
Truecolor, while pretty, is strictly an appearance feature. I'd like to able to use bpytop for its ability to display a wide variety of useful process and system information in a single terminal, without having to install a new terminal. (Other than bpytop, Terminal.app serves all my needs.)

I have patched bpytop locally to use the 256-color xterm color cube, and it looks acceptable, if not quite as nice as on a truecolor terminal:
![image](https://user-images.githubusercontent.com/9729801/98428779-f5063380-2057-11eb-8b86-b94a8e986b19.png)
I can submit a PR if acceptable.

**Comment by aristocratos** [comment]
@mspielberg 
> I can submit a PR if acceptable.

Feel free to do so.

I could probably add 256 color mode and 16 color mode as options in the theme files. To add the option for proper themes for those modes. The problem is the gradient arrays.
16 colors isn't a problem since that would just be the defined start, mid and end values split between 0-100 and no generated colors in between.
256 colors is a problem though since I'm not sure how the logic works there, but if you have a good handle on it we could probably make it work.

**Comment by byronmccollum** [comment]
It seems to work OK in Terminal.app if you run via `tmux`.

**Comment by aristocratos** [comment]
@mspielberg 
Added in v1.0.57
