### ISSUE TITLE
[REQUEST] Generate deb and rpm packages and msix

### ISSUE THREAD

**Issue by WSLUser** [aristocratos/bpytop#19]
**Is your feature request related to a problem? Please describe.**
I want to see packages published from Azure CI/CD to the Release Page to more easily install this without having to clone and make. 
**Describe the solution you'd like**
Fedora/CentOS does this as well as Debian/Ubuntu just mention the major distros for deb/rpm. If they are created here, they are more likely to be brought into upstream. Using msix would allow publishing into the MS Store for easy installation though just having an msix on github is enough due to winget, chocolately, scoop, etc.
**Describe alternatives you've considered**
Build yourself. 
**Additional context**
Azure CI/CD is free for OSS projects and should help with creating packages.

**Comment by WSLUser** [comment]
I see there are bunch of repos to choose from now but still no Windows support. Since python is platform-agnostic, this utility should be able to run on Windows. However I have seen no explicit mention of support for Windows. This issue was created for packaging not just for Linux but also Windows. If Windows isn't properly supported yet, then I will file issue requesting that support

**Comment by aristocratos** [comment]
@WSLUser 
Windows compatibility was never in the plans when I started this, so multiple libraries are *nix dependent. Also the input/output control and some pathing is reliant on *nix. And most escape codes used for colors and text control are based on unix standards.
Don't even know how well (if at all) 24-bit colors works in the shell for Windows.

Feel free to open a request for Windows support, but know that unless someone else takes it upon them to make that happen, it will likely be a long time before I get to it since it would be a lot of work.
