### ISSUE TITLE
[REQUEST] Move args parsing to "main"

### ISSUE THREAD

**Issue by jellonek** [aristocratos/bpytop#192]
At the moment you are parsing script args in main module, even if it would be imported as a module (e.g. from tests).
IMO this should be moved into `main()` so it would be executed only when script is supposed to run as a program.

**Comment by aristocratos** [comment]
@jellonek 
I don't see why that would matter. You're not passing arguments when importing so it really doesn't have any impact, or am I missing something?
And wouldn't be able to catch any errors before main with the `--debug` flag if it's moved.
Also makes a lot of sense to have the `-v` or `-h` flags to print and exit at the beginning instead of the end of the file.
