### ISSUE TITLE
[REQUEST] The ability to disable the resizing screen (except when window is too small)

### ISSUE THREAD

**Issue by drazil100** [aristocratos/bpytop#20]
I use a dropdown terminal and every time I drop it down bpytop displays the resizing screen for a second. It would be nice if I could disable the resizing screen when there isn't a problem so I don't need to wait a second to use bpytop every time I bring my terminal up. I understand the need to display the resizing screen though if the window is too small.

**Comment by aristocratos** [comment]
The resizing screen is there because any output during resize is broken so disabling it wouldn't display any useful information but just broken output.

But does the terminal you are using have to resize while showing/hiding? I would have thought it would have been a graphics effect rather than actually rolling up/down by resizing the line height?

**Comment by drazil100** [comment]
I have no idea. I am using Tilda 1.5.2 on manjaro btw. Whats interesting is version 1.4.1 on ubuntu 18.04 doesn't have this issue. I can't find a setting to change this unfortunately.

**Comment by aristocratos** [comment]
Could it be the window decorator or the window manager doing something with the window? Like trying to decorate > detecting borderless > refresh size, or something like that.

**Comment by drazil100** [comment]
I have disabled window effects so idk. I have submitted an issue to tilda too so they can investigate.
