### ISSUE TITLE
[REQUEST] FAN MONITORING AND CONTROL

### ISSUE THREAD

**Issue by scarpma** [aristocratos/bpytop#201]
**Is your feature request related to a problem? Please describe.**
I've always liked to monitor and control my fans velocity manually or based on rules that I define. I've still not found a good, easy extendable tool to do this on linux.

**Describe the solution you'd like**
The possibility to add a tab with velocity for each fan of the pc. Something as easy as:
##########################
MOD : DEFAULT / FIXED / PERSONALIZED
FAN 1 : 2000 RPM
FAN 2 : 3500 RPM
##########################
In addiction to this some option to set fixed values (with some security measure) or personalized function based on cpu temps, gpu or something else. Some possible "PERSONALIZED" options could be:
 - 'LINEAR': two values of temperature which correspond to min and max fan velocities. Intermediate temps are linearly mapped to intermediate fan velocities.
 - '...'
 - 'OTHER': same as above, but with the option to define a personalized function in python for the mapping.

**Describe alternatives you've considered**
I've always used ["Mac fan control"](https://crystalidea.com/macs-fan-control) for my macbook. But the implementation in bpytop would be so much better.

**Comment by aristocratos** [comment]
@scarpma 
There is support for showing fan speed in psutil https://psutil.readthedocs.io/en/latest/#psutil.sensors_fans but only on Linux.
And I don't know of a universal way of controlling the fan speeds for all motherboard chipsets in python.
I'm also not sure how feasible this is, it would be a pretty substantial amount of coding needed, for different chipset compatibility, fan curve controls and monitoring. And since it would require bpytop to take over fan speed control, in event of crashing your system would be at the risk of overheating.

I think the far better option would be to actually use software dedicated to fan control.

**Comment by scarpma** [comment]
I understand. Anyway, even just monitoring fan speed would be awesome. Thank you very much for your reply.
I will try to look into psutil.
