### ISSUE TITLE
[BUG] Higher than expected CPU usage (10%)

### ISSUE THREAD

**Issue by atheistd** [aristocratos/bpytop#223]
**bpytop uses at min 5% on my Ryzen 9 3900 XT and upto 20% on a Raspberry Pi 4**

bpytop uses more resources than a resource monitor should. My beast 12 core CPU shows *at min* 5% (hovers around 8% to 12%), similar results on my quad-core MacBook Pro - around 5% to 6.5% CPU load; It's worse on my Raspberry Pi 4 Model B with CPU util reaching around 20%. 

**To Reproduce**

Execute `bpytop`.

**Expected behavior**

I understand that bpytop relies on python3.x and hence is resource intensive, but this looks a bit too much. I would understand if I got the higher-than-expected-cpu-load problem on just one machine, but it is a consistent trait on all of my systems.

I use bpytop to monitor CPU util when I convert a few movies form h.264 to h.265 and it is useful to show ffmpeg load across all cores; I also have periodic zfs snapshots sent over to my Pi over the network - increasing CPU load more. I can't afford more load that baby.

This is a low priority bug to me and doesn't need to be resolved right away but I did point it out for the reason being *a resource monitor should not be resource intensive*.

**Info**
 - bpytop version: `1.0.52`
 - psutil version: `5.8.0`
 - (Linux) Linux distribution and version:
 `Linux sentinel 5.4.0-1025-raspi #28-Ubuntu SMP PREEMPT Wed Dec 9 17:10:53 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`
`Linux flameboi 5.8.0-7630-generic #32~1607010078~20.04~383a644-Ubuntu SMP Thu Dec 3 19:14:47 UTC 2 x86_64 x86_64 x86_64 GNU/Linux` (this actually is Pop!_OS)
 - (OSX/FreeBSD) Os release version: `Darwin Prathams-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64`
 - Terminal used: `terminator` on Raspberry Pi and workstation and `alacritty` on macOS
 - Font used: [Fira code](https://github.com/tonsky/FiraCode)
 - Python `3.8.5` (on all machines)

**Additional context**

contents of `~/.config/bpytop/error.log` (with `--debug` flag)
```
28/12/20 (08:26:17) | INFO: New instance of bpytop version 1.0.52 started with pid 180933
28/12/20 (08:26:17) | INFO: Loglevel set to DEBUG
28/12/20 (08:26:17) | DEBUG: Using psutil version 5.8.0
28/12/20 (08:26:17) | DEBUG: CMD: /home/ubuntu/.local/bin/bpytop --debug
28/12/20 (08:26:17) | DEBUG: Collect and draw completed in 0.599413 seconds
28/12/20 (08:26:17) | DEBUG: Init completed in 0.654459 seconds
```

**Comment by aristocratos** [comment]
@atheistd 
> bpytop uses more resources than a resource monitor should. My beast 12 core CPU shows at min 5% (hovers around 8% to 12%), similar results on my quad-core MacBook Pro - around 5% to 6.5% CPU load; It's worse on my Raspberry Pi 4 Model B with CPU util reaching around 20%.

Those numbers are pretty useless without any reference. 
* What are you using to measure cpu usage?
* Are the percent for the whole cpu or per core?
* What are your cpu frequency at the time of the sampling?
* What are your bpytop update timer set to?
* What other options is set in bpytop (tree, mem bytes, etc)?

Bpytop uses psutil for almost all system monitoring and psutil uses C extensions for low level operations to speed things up.

You can clone psutil and run the api speed test with:
```bash
git clone https://github.com/giampaolo/psutil.git
cd psutil
scripts/internal/print_api_speed.py
```

In comparison bpytop at standard settings uses less cpu than [glances](https://github.com/nicolargo/glances) (python), about the same as [gtop](https://github.com/aksakalli/gtop) (Node.js) and [gotop](https://github.com/xxxserxxx/gotop) (GO), about double of [bottom](https://github.com/ClementTsang/bottom) (rust) and about 3X that of [ytop](https://github.com/cjbassi/ytop) (rust).

With an 8 core i7 clocked at 3.6Ghz and bpytop at default settings with 2000ms update you should see around 3-6% single core cpu usage and around 0.1-0.5% total system cpu usage from bpytop.

If you don't need process monitoring you can toggle it off with two presses of the `m` key to drastically reduce cpu usage, since the iteration over running processes is what uses most of the cpu time.

**Comment by atheistd** [comment]
> What are you using to measure cpu usage?

I'm looking at it with `cpu_lazy` and `per-core` off/disabled/unselected in bpytop.

> What are your cpu frequency at the time of the sampling?

It's around 2.0 GHz on my Raspberry Pi 4; It hovers around 2.2 GHz and 2.4 GHz on my Ryzen 3900 XT and also on my Macbook's i5-8259U (when I amidling).

> What are your bpytop update timer set to?

I've been using 1000ms on Linux and 800ms on macOS. But at the time of writing this I've tried with the default 2000ms and I have the same result.

> What other options are set in bpytop?

I have made almost no changes to the config file - except to set `show_init=False`.

I do need the mode to be full; *It's fancy that way.*

**Comment by aristocratos** [comment]
@atheistd 
> I've been using 1000ms on Linux and 800ms on macOS. But at the time of writing this I've tried with the default 2000ms and I have the same result.

I don't think I believe you, increasing the update time to double of what you had before can't result in the same cpu usage. Try checking the cpu usage of bpytop with `top` or `htop` with 1000ms and 2000ms update time respectively.

> I do need the mode to be full; It's fancy that way.

Well that fancy eats cpu.

I could possibly decouple the update timer for processes and all the other stats in a future version which could alleviate the cpu usage, for example 1000ms for processor, memory and network while processes update at 5000ms, since the process stats uses maybe 5/6 of the overall cpu usage.

Other than that there is really nothing I can do about the cpu usage since it falls in the realm of https://github.com/giampaolo/psutil code and not bpytop code.

**Comment by atheistd** [comment]
The utilization between 1000ms and 2000ms is identical (on my x86 machines). There is about 2% difference. Whereas I used 100ms for a minute on my Pi and it went to 100% on one of my core on Raspberry Pi. On 100ms, it hovers between 70% to 100% usage on one core. Looking at the cpu util of bpytop from htop is a different story. At 2000ms, it is between 11% to 40%. At 1000ms it is between 37% and 68%.

> I don't think I believe you, increasing the update time to double of what you had before can't result in the same cpu usage.

I thought so myself. The CPU utilization difference between 1000ms and 2000ms is more pronounced on Raspberry Pi - the only machine whose resources I want to take a look at - than the other 2 systems. Also, I overlooked that difference as there was an ongoing scrub and now that it is complete, I can confirm that it is there, but just not as much (around 2%) on my x86 systems and as you said quite double utilization on my arm system.

> Well that fancy eats cpu.

Couldn't agree more lol

> I could possibly decouple the update timer for processes and all the other stats in a future version which could alleviate the cpu usage, for example 1000ms for processor, memory and network while processes update at 5000ms, since the process stats uses maybe 5/6 of the overall cpu usage.

Yeah I see how that might affect cpu usage, and that does sound like a good idea. I have no idea how much work this is, or how much I can help (as I've not got free enough to look at the source code yet) but this is my proposed solution. (could be totally wrong as earlier stated by me, I've not looked a the source code yet)

Assuming update interval is set to 1000ms and assuming that the user is looking at the full view mode. After every 200ms (one fifth of the update interval), update all the numbers of a single field - i.e. get the numbers for memory usage, then 200ms later, get numbers for network view; so on and so forth. Do this first for memory, then network, then the cpu and then the processes view so that 800ms are well spent and don't the tax the cpu *as much* if you were to do all of it in one go. And at the end of 1000ms cycle, update (display) the view with new numbers. i.e. don't do all the work when your 1000ms update time cycle is about to end;

I started watching this repo for releases and will continue watching until either someone from your team solves this problem or I'll look at doing it myself and push the changes after a week. Whichever is sooner. :')

**Comment by aristocratos** [comment]
@atheistd 

> Assuming update interval is set to 1000ms and [...] i.e. don't do all the work when your 1000ms update time cycle is about to end;

This makes no difference at all. The CPU usage is calculated by how much resources has been used between two points in time, so no matter when between those two points the work gets done, the end result is exactly the same. And the actual time to collect all stats are about 150ms on a modern CPU, where around 100ms alone is the process collection.

> [...] until either someone from your team solves this problem [...]

There's no team. Only me.

> [...] or I'll look at doing it myself and push the changes after a week.

Please do. I'm not quite sure which changes those are, but anyone is free to open a pull request.

Again however I'm going to refer you to https://github.com/giampaolo/psutil if you want to improve CPU usage, since it's the library used for most system info gathering in bpytop.

**Comment by atheistd** [comment]
Okay, I'll experiment with bpytop first (as I don't like fiddling with libraries right away) and then look into psutil if the first solution doesn't help. Closing the bug. :')
