### ISSUE TITLE
[REQUEST] Allow abriviating CoreXX to XX

### ISSUE THREAD

**Issue by Licenser** [aristocratos/bpytop#25]
**Is your feature request related to a problem? Please describe.**

With many cores or very constraint space, the CPU list uses a lot of extra space for `CoreXX` and starts to look unpleasant/confusing. Sometimes the C of Celsius and the C of Core and up being directly next to each other.

**Describe the solution you'd like**

Being able to abbreviate the `CoreXX` to a 2 (or 3) digit number would save some space

**Describe alternatives you've considered**

* `cXX` would be an alternative solution
* this could, instead of a config option be an automatic option when space gets tight
* It would be possible to just not show core number at all

**Additional context**
here an image (this looks kind of broken to me)

![image](https://user-images.githubusercontent.com/119093/89389671-fdbc3600-d705-11ea-9476-e3221a0df276.png)

**Comment by aristocratos** [comment]
They are not supposed to look like that... I realize I messed up when simulating more cores for testing, I reused the same core number for all extra cores and since the system I'm developing on only has 8 cores I didn't account for double digits...

But yeah, can add an extra step of changing "Core" to "C" to save some more space.

**Comment by aristocratos** [comment]
Fixed in v1.0.4
Also changed "Core" to "C" by in all adaptable sizes and added divider line.

**Comment by Licenser** [comment]
tested it looks great :) thank you so much for the quick resolution! <3
