### ISSUE TITLE
[BUG] 101% in battery

### ISSUE THREAD

**Issue by ShrirajHegde** [aristocratos/bpytop#253]
**Describe the bug**

101% in battery

**To Reproduce**

just launch bpytop when battery is at 100%
![image](https://user-images.githubusercontent.com/66936172/105635810-0870b000-5e8b-11eb-8cec-0386254ae78e.png)

**Expected behavior**

[A clear and concise description of what you expected to happen.]

**Screenshots**
![image](https://user-images.githubusercontent.com/66936172/105635823-1d4d4380-5e8b-11eb-8cce-e9afb6df4005.png)

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
bpytop version: 1.0.60
psutil version: 5.7.3

 - (Linux) Linux distribution and version:Ubuntu 20.04
 - Terminal used:Gnome Terminal
 - Font used:MesloLGS NF
 - Python version,Python 3.8.5(version 3.6 or above is required):

**Additional context**

contents of `~/.config/bpytop/error.log`

(try running bpytop with `--debug` flag if error.log is empty)

**Comment by aristocratos** [comment]
@ShrirajHegde 
The only way for this to happen is if your system is reporting current energy as above maximum capacity for the battery, in which case the percentage above 100% is accurate.

So this would be working as intended and also notify you if your battery is being overcharged.

I could add a max value at 100%, but that would make it less accurate because of the reasons above.

**Comment by ShrirajHegde** [comment]
Is there any manual way I can check it?
