### ISSUE TITLE
[REQUEST] show CPU wa / %iowait / disk %util by default

### ISSUE THREAD

**Issue by slrslr** [aristocratos/bpytop#268]
bpytop version: 1.0.61
psutil version: 5.8.0

Hello,
other monitoring utilities shows important parameter which is CPU wait and disk utilization. I am missing this in bpytop.

glances shows iowait (CPU_IOWAIT) percentage
top shows "wa" which is possibly same value as glances reports
"iostat -x" shows possibly same value as %iowait and additionally shows disk %util value (% utilization - related to iops, not just MB/s).

It would be handy if bpytop by default whows cpu iowait percentage and also percentage of the disks utilization with maybe possibility to select which drive utilization to display (in my case system SSD drive utilization is not the problem, but the external HDD is the drive of interest.

The "disks" section shows disk space usage by default, i think by default should display I/O utilization instead. It currently shows my system drive bandwidth which does not interest me, what interest me is my external HDD transfers per second, bandwidth per second and above mentioned total utilization %... Maybe it can display these statistics for the most %util drive automatically or user select the drive.

**Comment by aristocratos** [comment]
@slrslr 
![scrsht](https://user-images.githubusercontent.com/59659483/108622301-21439580-7438-11eb-9185-8b83c9125bb6.png)

1. CPU iowait can be selected as one of the cpu graphs if your system exposes it, look in the cpu options menu.
2. Drive read/write speeds are shown in realtime next to the disk label
3. Disk io stats (read/write) are shown under the label if they are available

If no speed text/stats are shown for your external HDD, then those stats aren't exposed by any standard methods.

**Comment by aristocratos** [comment]
Also, press the `i` key or the `io` button to only show disks IO stats with larger graphs.

**Comment by slrslr** [comment]
1. i do not see that iowait figure like on your screenshot. I see:
![](https://imgur.com/hqHDLBA.png)
and in the Options i do not see any thing that looks to be related to enabling it.

2. > Drive read/write speeds are shown in realtime next to the disk label

I was not talking about the IO, but utilization percentage and transfers/second. Moreover it shows IO of the system drive which i am not interested in as the system drive is SSD, i am interested in my external HDD as i have described

> If no speed text/stats are shown for your external HDD

glances shows my external drive read and write MB/s and nmon utility shows disk transactions per second and my ext. HDD utilization%, i do not see any of these in bpytop for my external drive (actually do not know how to switch to it, i think it should display most utilized drive by default with option to manually switch to other one).

> press the i key or the io button

it shows IO, not iops (transactions per second or disk util%) and moreover it shows it for system drive which is SSD, i am interested into my external HDD which is mounted and stats shown in iostat, nmon, glances utilities.

**Comment by aristocratos** [comment]
@slrslr 
> i do not see that iowait figure like on your screenshot [...] and in the Options i do not see any thing that looks to be related to enabling it.

The first and second items in the cpu options selects what graphs to show.

> glances shows my external drive read and write MB/s and nmon utility shows disk transactions per second and my ext. HDD utilization%, "iostat -x" too

The partition info and io stats collected from the system need to be paired by comparing /dev/ names, if they aren't easily comparable the stats won't be shown since bpytop don't know if it's the correct information.

Can you run
`python3 -c "import psutil, pprint; pprint.pprint(psutil.disk_partitions(all=False))"`
`python3 -c "import psutil, pprint; pprint.pprint(psutil.disk_io_counters(perdisk=True))"`
and post the output?

> it shows IO, not iops (transactions per second or disk util%) and moreover it shows it for system drive which is SSD, i am interested into my external HDD which is mounted and stats shown in iostat, nmon, glances utilities.

It shows stats for all drives, if it only shows your system drive, then it's the only one io stats was found for.

See https://psutil.readthedocs.io/en/latest/#disks for what io stats are available, read/write bytes are used because it's the far more relatable stat over using read/write count.

**Comment by slrslr** [comment]
> The first and second items in the cpu options selects what graphs to show.

indeed, one of the displayed figures is iowait. It does not show any value, so i can only guess it, ok. But i think more meaningfull and space saving would be iowait numerical value displayed somewhere by default.

> Can you run ... and post the output?

[here](https://bin.disroot.org/?feef56c7b3c869fc#5pP8hfZXHuQYNaMHG29eub1m9mzMdQPgPnMG7ri8yqQV) please for privacy. sdb is the ext. HDD of interest.
Hopefully bpytop will be able to display disk utilization and transfers per second similar to what other tools like glances, iostat, nmon display.

**Comment by aristocratos** [comment]
@slrslr 
> But i think more meaningfull and space saving would be iowait numerical value displayed somewhere by default.

You're the only one who has ever mentioned this value as an important stat, so showing it by default doesn't seem like a sensible option when 99% of people don't see it as important.
However, adding an option for also showing the numerical % of the graph could be done.

> Hopefully bpytop will be able to display disk utilization percentage and transfers per second similar to what other tools like glances, iostat, nmon display.

Disk utilization percentage isn't a reported stat but would be a calculation and not very accurate of actual disk use, unless you actually benchmark the disks max io troughput at every start.
Transfers per second (number of read/write count per second) is just like cpu iowait something nobody has showed any interest in before and will unlikely be something I spend time on when there is plenty of other stuff that needs attention.

The current design philosophy in BpyTOP is: Readability > Design > Verboseness.
If you want a "wall of text" with every possible stat shown, glances is the tool you want.
If you want minimalistic and fast, htop is the one.
If you want big truecolor graphs and an easy-to-understand interface, bpytop is it.

From the output you posted, the issue seems to be your zfs filesystem. The device names from `psutil.disk_partitions` can't be related to the device names in `psutil.disk_io_counters`.
So it can't be determined which io stat entry belongs to which partition.
The support for zfs partition stats is already poor without external tools see #78, so this is unlikely to be fixed before there is proper zfs support.

**Comment by slrslr** [comment]
If you think that the disk tps (for example reported by iostat, nmon is not accurate and have better things to do, i understand.
Though i think that the disk utilization% (reported by iostat) and iowait (reported by top and others) are important measures (even if not 100% accurate) to quickly get the clue about the bottleneck on the computer. Because it is not available in bpytop (iowait is, but not by default and does not show the % value). And bpytop does not support my ext. drive sdb IO/tps stats, i will continue with glances, nmon. But as you have said bpytop has its own advantages. Good work. Thank you
