### ISSUE TITLE
CPU usage of bpytop itself

### ISSUE THREAD

**Issue by jtgd** [aristocratos/bpytop#286]
According to bpytop, bpytop is using 1.2% of the CPU:

> 4189134 python3 python3 /usr/bin/bpytop  3 jay  42M ⣀⣀⣀⣀⣀  1.2

According to 'inxi -t' bpytop is using 8.9% of the CPU:
> 1: cpu: 8.9% command: bpytop started by: python3 pid: 4189134

Can anyone explain, and which one is correct?

**Comment by aristocratos** [comment]
@jtgd 
Both are correct, `inxi` is showing CPU usage per core, `bpytop` is showing CPU usage for the whole CPU, unless you press `c` to toggle the "per-core" option.

**Comment by jtgd** [comment]
Thanks. I do see that selecting "per-core" does make it match, although it seems more like "sum of all cores".

This question was a prelude to my real question: why does bpytop take 9% of my CPU?  That seems like a lot and I wasn't sure if it was because of something I have configured or if it is really that busy. If this is normal then I'll probably not leave bpytop running constantly.

**Comment by aristocratos** [comment]
@jtgd 
> This question was a prelude to my real question: why does bpytop take 9% of my CPU? 

It doesn't. It uses 8.9% of one CPU core/thread on your particular system. It only uses 1.2% of your CPU.

> If this is normal then I'll probably not leave bpytop running constantly.

How much CPU time it needs depends on your CPU, if you think it's too much then don't run it constantly, you're unlikely to find a resource monitor with a comparable amount of information shown, that uses less CPU.

You can increase your update timer in the options, which would directly impact CPU usage.
You can also increase "Proc update mult" in the options, since the process iteration is whats using most CPU time.

**Comment by jtgd** [comment]
Understood. Thank you.
