### ISSUE TITLE
Python error on Fedora 35

### ISSUE THREAD

**Issue by shamblett** [aristocratos/bpytop#364]
The utility works great on stock Fedora 35 however when I exit I get this message -
```
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import strtobool
```

**Comment by RCristiano** [comment]
+1

**Comment by etiennepellegrini** [comment]
Seeing this on macOS 11.6.1, with bpytop 1.0.67 installed through Homebrew.
The problem comes from `distutils.utils`, from which `strtobool` is imported and used only once.

Per [PEP 632](https://www.python.org/dev/peps/pep-0632/):
>  For these functions, and any others not mentioned here, you will need to reimplement the functionality yourself. The legacy documentation can be found at https://docs.python.org/3.9/distutils/apiref.html
>  [...]
> `distutils.util.strtobool`

The solution is to implement the [functionality described here](https://docs.python.org/3.9/distutils/apiref.html#distutils.util.strtobool). Something like:
```python
def strtobool(val):
    try:
        if val.lower() in ['y', 'yes', 't', 'true', 'on', '1']:
            return True
        elif val.lower() in ['n', 'no', 'f', 'false', 'off', '0']:
            return False
        else:
            raise ValueError(f"invalid truth value {val}")
    except:
        raise ValueError(f"invalid type {type(val)} for truth value {val}")
```

(note that the `.lower()` is not documented, but `strtobool` does accept the capitalized versions of the flags as True or False, and throws an error when called on something else than a `str`)

**Comment by UmarJ** [comment]
You can see how it's implemented in the source [here](https://github.com/python/cpython/blob/f62420c3d3f5d87f2b57e54b2a98682bc835f7b6/Lib/distutils/util.py#L308-L321).
