### ISSUE TITLE
Can't install on OpenSUSE 15.2 [BUG]

### ISSUE THREAD

**Issue by RafaelLinux** [aristocratos/bpytop#71]
**Describe the bug**
After I did `python3 -m pip install psutil` it ends with an error `pygobject 3.34.0 requires pycairo>=1.11.1, which is not installed.` . Then I installed `python3-cairo ` .After than, I got error `Using legacy 'setup.py install' for psutil, since package 'wheel' is not installed.`. I installed `python3-wheel`. 
Then I got `You are using pip version 10.0.1, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.` and I updated `pip` with mentioned command. 
Finally, I downloaded bpytop.py and I did `python3 bpytop.py` and all gone right.

So please, add in "requirements":
- python3-cairo
- python3-wheel

Thank you!!
**Info (please complete the following information):**
- bpytop version: 1.0.16
- psutil version: 5.4.8
- OpenSUSE 15.2 x64 Linux
- Python 3.6.10

**Comment by aristocratos** [comment]
> psutil version: 5.4.8

5.7.0 is the required psutil version and the only dependency besides python 3.6> itself.

Listing dependencies of dependencies doesn't seem sane since we could continue that game down to the linux kernel itself.

pip should install all dependencies needed for psutil when running `pip3 install psutil` but:

> You are using pip version 10.0.1, however version 20.2.2 is available

pip 10.0.1 is over 2 years old so could have something to do with it.
