### ISSUE TITLE
[REQUEST] Change menu shortcut back to small _m_

### ISSUE THREAD

**Issue by RedBearAK** [aristocratos/bpytop#76]
I have been using BashTOP and now BPyTOP for a few months and got used to the menu shortcut being the small "m". 

I always hesitate before hitting escape because I feel like it might exit the application. That is kind of the standard behavior of the escape key in most situations, to either "stop/cancel" something or "leave". 

With the advent of the new Mini mode, you chose to let Mini mode use the small "m" key. 

Maybe I'm biased from using older versions of BashTOP/BPyTOP, but I think this was a mistake. 

Think about how frequently someone will want to shift between Mini mode and regular mode. I don't think most people are going to be toggling the display mode more than once per session. 

On the other hand, think about how frequently we get into the menu to mess with settings and themes, especially as we are getting used to BPyTOP as a new application. I've probably been in that menu hundreds of times by now, playing around with different settings. I'm still getting tripped up by hitting "m" like I used to and accidentally toggling Mini mode when I just want the menu. 

Please consider swapping the small "m" key back to opening the menu, and letting Shift+M toggle the display mode. It feels like that would be much more convenient for the typical user.

**Comment by drazil100** [comment]
This was originally changed idue to #15 under the assumption that mini mode would be the more useful option to quick toggle.

The menu already has 1 key that doesn't require shift dedicated to it (esc) however if that bothers you you can always skip the menu and go straight into and out of options with "o" (or alternatively F2) and bypass the menu entirely.

**If** this isn't an acceptable solution @aristocratos DID suggest the possibility of custom hotkeys though I can't imagine it being worth the effort over this when the controls are otherwise so straightforward and intuitive. Either way I do not think its a good idea to require you to press 2 keys to switch between mini mode to give something that already has a 1 key option a second 1 key option.

**Comment by aristocratos** [comment]
As @drazil100 said, these bindings has already been changed once for good reason. And the lowercase "m" for mini mode is a lot more useful on smaller terminal sizes than as an extra shortcut for the menu.
